server:
  port: 3344
spring:
  application:
    name: cloud-config-center    #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:PZF1004/SpringCloud2020-config.git #GitHub上面的git仓库名字
          search-paths:   #搜索目录
            - SpringCloud2020-config
      label: main #读取分支
  #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: "bus-refresh"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka