server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh                    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service      # 动态路由：lb://微服务名
          predicates:
            - Path=/provider/payment/get/**    # 断言，路径相匹配的进行路由

        - id: payment_routh2                   #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          filters:
            - AddRequestHeader=X-Request-Id, 1024  # 过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024
          predicates:
            - Path=/provider/payment/lb/**     # 断言，路径相匹配的进行路由
            #- After=2021-02-18T12:24:30.005+08:00[Asia/Shanghai]   # 在这个时间之后才能访问
            #- Cookie=username,pzf  #必须有cookie：username=pzf
            #- Header=X-Request-Id, \d+    # 请求头要有X-Request-Id属性并且值为整数的正则表达式
            #- Query=username, \d+  #要有参数名username并且值还要是整数才能路由
eureka:
  instance:
    hostname: cloud-gateway-service  # eureka服务端的实例名称
  client:
    service-url:
      register-with-eureka: true  # false表示不向注册中心注册自己
      fetch-registry: true  # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
      defaultZone: http://eureka7001.com:7001/eureka